### PR TITLE
Disable raw mode on panic

### PR DESCRIPTION
**Pull request by KilianVounckx**
Fixes [this issue](https://github.com/roc-lang/basic-cli/issues/69)

### CODE REVIEW

**Review by Anton-4 — CHANGES_REQUESTED** [review]
Thanks for your contribution @KilianVounckx!
In the atomic bool docs I saw that " This type is only available on platforms that support atomic loads and stores of u8.", so I'd like to fall back to the std bool using `#[cfg(target_has_atomic = "8")]`. Given that this complicates things I'd also like to move the bulk of this complexity to a separate file.

What do you think? Feel free to take your time :)

**Comment by KilianVounckx** [comment]
If I understand correctly, you want to fall back on a normal (non atomic) bool? Wouldn't this break multi-threading?

**Comment by Anton-4** [comment]
Yeah, I was thinking about sacrificing that as a trade-off.
Thinking about it more, I believe the functions in Tty.roc are out of scope for basic-cli, I'm going to start a discussion on zulip.

**Comment by Anton-4** [comment]
Based on the discussion on zulip, let's go with the proposed `disable_raw_mode` on panic, without inspecting the current state.

**Review by Anton-4 — APPROVED** [review]

**Pull request merged**
