### PR TITLE
Change the args example to use Weaver

### PR DESCRIPTION
**Pull request by smores56**
The internal `Arg` module has been finicky, so I've replaced the `argsBROKEN.roc` example with a working one using the new CLI parser I wrote, [Weaver](https://github.com/smores56/weaver). It's basically the same as the previous example, except instead of performing division and logarithm, I'm doing division and max number in a list since log isn't implemented on linux x86 yet.

### CODE REVIEW

**Review by lukewilliamboswell — APPROVED** [review]
Looks nice. 😀

**Comment by Anton-4** [comment]
Thanks @smores56! Nice to have a working args example :tada:

**Comment by smores56** [comment]
@lukewilliamboswell since this got merged already, not this time, but I'll try to remember for future changes. [The CONTRIBUTING.md doc](https://github.com/roc-lang/roc/blob/main/CONTRIBUTING.md#commit-signing) explains what to do well.

**Comment by lukewilliamboswell** [comment]
@smores56 no worries 👍 😃

**Pull request merged**
