### PR TITLE
Add modules to `exposes` in `main.roc`

### PR DESCRIPTION
**Pull request by rtfeldman**
This should fix docs generation

### CODE REVIEW

**Comment by Anton-4** [comment]
Posting the error here for easy viewing:
```
Run ./roc_nightly/roc build ./examples/env.roc

thread '<unnamed>' panicked at 'Ability specialization is unknown - code generation cannot proceed!', crates/compiler/mono/src/ir.rs:5829:30
```

**Comment by Anton-4** [comment]
Let's see if this error still occurs...

**Comment by Anton-4** [comment]
The error still occurs but is more specific now:
```
thread '<unnamed>' panicked at 'Ability specialization is unknown - code generation cannot proceed!: NoTypeImplementingSpecialization', crates/compiler/mono/src/ir.rs:5788:10
```

**Comment by rtfeldman** [comment]
@ayazhafiz any idea what this error might be referring to?

**Comment by Anton-4** [comment]
This only occurs with the changes here, could it be that the glue code needs to be updated?

**Comment by ayazhafiz** [comment]
Ok, so probably glue is picking up the exposed types in `EnvDecoding` and attempting to generate code for them, which is a problem, since those types are not material until their ability variables are instantiated.

**Comment by rtfeldman** [comment]
I can reproduce the error CI is getting locally by:

1. Checking out the `add-exposes` branch of `basic-cli` locally
2. Doing `roc build examples/env.roc`

It doesn't reproduce on the `main` branch of `basic-cli'.

@ayazhafiz maybe it has to do with platforms as opposed to applications, rather than glue vs build?

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/roc-lang/basic-cli/pull/28

**Pull request closed without merging**
