### PR TITLE
Change the type of Stdin.line to Task [Input Str, End] *

### PR DESCRIPTION
**Pull request by isaacvando**
In reference to [this zulip thread](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Reading.20Stdin.20until.20EOT.3F)

In my first commit I added a `piping.roc` example, but I have not figured out how to write an expect script for it successfully. If you think it is valuable, feel free to add it back with a test.

### CODE REVIEW

**Comment by Anton-4** [comment]
I found a segfault when running examples/stdin.roc or examples/piping.roc. I also found out that our tests don't check for segfaults so I'm going to fix that first.

**Comment by Anton-4** [comment]
Hmm the segfaults only seem to occur on NixOS (even on main branch), not on ubuntu.

**Review by Anton-4 — APPROVED** [review]
Thanks @isaacvando :)

**Comment by isaacvando** [comment]
Thanks @Anton-4 !

What are those expect scripts? I couldn't find anything about them online when I googled.

**Comment by Anton-4** [comment]
[This link](https://phoenixnap.com/kb/linux-expect) gives a nice overview.

**Pull request merged**
