### PR TITLE
Update API for main

### PR DESCRIPTION
**Pull request by lukewilliamboswell**
[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/383402-API-Design/topic/Stdin.2Eline/near/434596697)

Note this also includes the commits from https://github.com/roc-lang/basic-cli/pull/182

Some of the examples aren't optimal and can be simplified in future -- I've had to workaround [this bug](https://github.com/roc-lang/roc/issues/5477) in some places (e.g. hello-world) so there are no warnings so CI can pass. We can clean these up further once https://github.com/roc-lang/roc/pull/6658 merges.

I've added the new `Cmd.exec : Str, List Str -> Task {} Error` helper, and modified `examples/command.roc` so it also runs on macOS. It was proving too difficult to rely on linux CI to run to ensure the changes were correct with the subtle differences between `stat` on macOS and ubuntu. 

I removed some of the unicode characters from examples as this was causing a segfault in the expect scripts, and I didn't track down the exact cause -- so this was a workaround that seemed acceptable to keep these working with CI.

**EDIT: to clarify the hello-world workaround...**

I have included an additional `Stdout.line` call as this prevents the following Warning which subsequently prevents CI from completing. The additional line will ensure there is a `!` unwrapped and therefore a `Task.await` will be added and so we don't get the unused warning. If we remove the import then the platform will error as it doesn't have `Task` imported. 

So until `Task` is a builtin, or we resolve transitive dependencies correctly; programs like this will throw an Warning when users have an app will a single suffix line, or where they do not use anything from the `Task` module.

```
── UNUSED IMPORT in examples/hello-world.roc ───────────────────────────────────

Nothing from Task is used in this module.

3│      imports [pf.Stdout, pf.Task.{ Task }]
                            ^^^^^^^^^^^^^^^^

Since Task isn't used, you don't need to import it.

────────────────────────────────────────────────────────────────────────────────

0 errors and 1 warning found in 688 ms
.

Running program…

────────────────────────────────────────────────────────────────────────────────
```

### CODE REVIEW

**Comment by Anton-4** [comment]
Thanks for this substantial effort @lukewilliamboswell!

I tried to cut out the exit code changes to avoid the hello world workaround https://github.com/roc-lang/basic-cli/pull/186 but ran into problems with the new Cmd errors. I think it's wise to call of the hacker news plans, I don't want to force things through in a rush. I'll talk to Richard. No big deal btw, software is hard sometimes :heart:

**Comment by lukewilliamboswell** [comment]
I don't think it's a major concern. The workaround is only required here to keep CI happy. Users can still write single line hello world apps, they will just get a warning until that module imports bug is fixed.

**Comment by lukewilliamboswell** [comment]
The exit code changes are not related to the bug, though I'm not sure why sometimes the module imports transitive dependencies were not complaining before we made the change. I think may have been the change in type signature that takes a different path in typecheck or something.

**Comment by lukewilliamboswell** [comment]
Included docs for the `Stdout`, `Stderr`, and `Stdin` error types.

Screenshot 2024-04-23 at 05 42 38

**Review by rtfeldman — APPROVED** [review]

**Comment by Anton-4** [comment]
> EDIT -- the changes are related to the bug through the introduction of the ! suffix which requires Task module to be imported by the application.

This also happens with the old hello world without `!`, I think it's purely due to the changes in platform/main.roc. I made #187 for tracking.

**Pull request merged**
